--CREATE USER SEMI5 IDENTIFIED BY SEMI5; 계정생성(관리자계정으로)
--GRANT CONNECT, RESOURCE TO SEMI5; 권한부여
--스크립트 실행용 DROP구문
DROP SEQUENCE SEQ_MEM_NO;
DROP SEQUENCE SEQ_MUS_NO;
DROP SEQUENCE SEQ_PLA_NO;
DROP TABLE RECORD;
DROP TABLE PLAYLIST;
DROP TABLE MUSIC;
DROP TABLE MEMBER;
--

-------------------------------------테이블--------------------------------------
--멤버테이블
CREATE TABLE MEMBER(
    MEM_NO NUMBER PRIMARY KEY,
    MEM_ID VARCHAR2(32) UNIQUE,
    MEM_PWD VARCHAR2(32) NOT NULL,
    PHONE VARCHAR2(32) NOT NULL,
    EMAIL VARCHAR2(32) NOT NULL,
    STATUS VARCHAR2(2) DEFAULT 'Y'
);

--뮤직테이블
CREATE TABLE MUSIC(
    MUS_NO NUMBER PRIMARY KEY,
    MUS_NAME VARCHAR2(100) NOT NULL,
    MUS_ART VARCHAR2(50) NOT NULL,
    MUS_GEN VARCHAR2(30),
    MUS_TIME VARCHAR2(10) NOT NULL,
    MUS_MV VARCHAR2(1000),
    STATUS VARCHAR2(2) DEFAULT 'Y'
);

--플레이리스트테이블
CREATE TABLE PLAYLIST(
    PLA_NO NUMBER PRIMARY KEY,
    PLA_NAME VARCHAR2(100) NOT NULL,
    PLA_ART VARCHAR2(100) NOT NULL,
    PLA_GEN VARCHAR2(30),
    PLA_TIME VARCHAR2(10) NOT NULL,
    PLA_STATUS VARCHAR2(10) NOT NULL,
    MEM_NO NUMBER REFERENCES MEMBER (MEM_NO)
);

--기록테이블
CREATE TABLE RECORD(
    MUS_NO NUMBER REFERENCES PLAYLIST (PLA_NO),
    MUS_NO2 NUMBER REFERENCES MUSIC (MUS_NO)
);


-------------------------------------시퀀스--------------------------------------
--멤버테이블의 멤버 번호 시퀀스 (2부터 시작하여 1씩 증가(1은 관리자 넘버)하고 최대99까지)
CREATE SEQUENCE SEQ_MEM_NO
START WITH 2
INCREMENT BY 1
MAXVALUE 99
NOCYCLE
NOCACHE;

--뮤직테이블의 노래번호 시퀀스(100부터시작 1씩증가 999까지)
CREATE SEQUENCE SEQ_MUS_NO
START WITH 100
INCREMENT BY 1
MAXVALUE 999
NOCYCLE
NOCACHE;

--플레이리스트 테이블의 PLA번호 시퀀스(1000부터 1씩증가 1999까지)
CREATE SEQUENCE SEQ_PLA_NO
START WITH 1000
INCREMENT BY 1
MAXVALUE 1999
NOCYCLE
NOCACHE;

------------------------------------더미데이터------------------------------------
--컨펌후 추가