--CREATE USER SEMI5 IDENTIFIED BY SEMI5; 계정생성(관리자계정으로)
--GRANT CONNECT, RESOURCE TO SEMI5; 권한부여
----------삭제-------------
--접속유저의 모든 테이블 및 제약조건 삭제
BEGIN
    FOR C IN (SELECT TABLE_NAME FROM USER_TABLES) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE '||C.TABLE_NAME||' CASCADE CONSTRAINTS');
    END LOOP;
END;
/

--접속유저의 모든 시퀀스 삭제
BEGIN
FOR C IN (SELECT * FROM USER_SEQUENCES) LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||C.SEQUENCE_NAME;
END LOOP;
END;
/

--접속유저의 모든 뷰 삭제
BEGIN
FOR C IN (SELECT * FROM USER_VIEWS) LOOP
  EXECUTE IMMEDIATE 'DROP VIEW '||C.VIEW_NAME;
END LOOP;
END;
/
--

-------------------------------------테이블--------------------------------------
--멤버테이블
CREATE TABLE MEMBER(
    MEM_NO NUMBER PRIMARY KEY,
    MEM_ID VARCHAR2(32) UNIQUE,
    MEM_PWD VARCHAR2(32) NOT NULL,
    PHONE VARCHAR2(32) NOT NULL,
    EMAIL VARCHAR2(32) NOT NULL,
    STATUS VARCHAR2(2) DEFAULT 'Y'
);

--뮤직테이블
CREATE TABLE MUSIC(
    MUS_NO NUMBER PRIMARY KEY,
    MUS_NAME VARCHAR2(100) NOT NULL,
    MUS_ART VARCHAR2(50) NOT NULL,
    MUS_GEN VARCHAR2(30),
    MUS_TIME VARCHAR2(10) NOT NULL,
    MUS_MV VARCHAR2(1000),
    STATUS VARCHAR2(2) DEFAULT 'Y',
    COUNT NUMBER DEFAULT 0,
    ALBUM_PATH VARCHAR2(4000),
    ENROLL_DATE DATE DEFAULT SYSDATE
);

--플레이리스트테이블
CREATE TABLE PLAYLIST(
--    PLA_NO NUMBER,
    MUS_NO NUMBER REFERENCES MUSIC(MUS_NO),
    MEM_NO NUMBER REFERENCES MEMBER (MEM_NO),
    STATUS VARCHAR2(3) DEFAULT 'Y'
);
--    PLA_NAME VARCHAR2(100) NOT NULL,
--    PLA_ART VARCHAR2(100) NOT NULL,
--    PLA_GEN VARCHAR2(30),
--    PLA_TIME VARCHAR2(10) NOT NULL,
--    PLA_STATUS VARCHAR2(10) NOT NULL,

--기록테이블
CREATE TABLE RECORD(
    MUS_NO2 NUMBER REFERENCES MUSIC (MUS_NO)
);

--ATTACHMENT테이블
CREATE TABLE ATTACHMENT(
    FILE_NO NUMBER PRIMARY KEY,
    REF_MNO NUMBER REFERENCES MUSIC(MUS_NO),
    ORIGIN_NAME VARCHAR2(300) NOT NULL,
    CHANGE_NAME VARCHAR2(300) NOT NULL,
    FILE_PATH VARCHAR2(2000),
    UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
    FILE_LEVEL NUMBER DEFAULT 1,
    STATUS VARCHAR2(3) DEFAULT 'Y',
    REF_MENO NUMBER REFERENCES MEMBER(MEM_NO)
);


-------------------------------------시퀀스--------------------------------------
--멤버테이블의 멤버 번호 시퀀스 (2부터 시작하여 1씩 증가(1은 관리자 넘버)하고 최대99까지)
CREATE SEQUENCE SEQ_MEM_NO
START WITH 2
INCREMENT BY 1
MAXVALUE 99
NOCYCLE
NOCACHE;

--뮤직테이블의 노래번호 시퀀스(100부터시작 1씩증가 999까지)
CREATE SEQUENCE SEQ_MUS_NO
START WITH 100
INCREMENT BY 1
MAXVALUE 999
NOCYCLE
NOCACHE;

----플레이리스트 테이블의 PLA번호 시퀀스(1000부터 1씩증가 1999까지)
--CREATE SEQUENCE SEQ_PLA_NO
--START WITH 1000
--INCREMENT BY 1
--MAXVALUE 1999
--NOCYCLE
--NOCACHE;

--ATTACHMENT 테이블의 FILE_NO 시퀀스
CREATE SEQUENCE SEQ_FILE_NO
START WITH 10000
INCREMENT BY 1
MAXVALUE 20000
NOCYCLE
NOCACHE;

------------------------------------더미데이터------------------------------------
--MEMBER데이터
INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (1,'admin','1234','010-1234-5678','member01@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member02','pass02','010-1234-5677','member02@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member03','pass03','010-1234-5676','member03@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member04','pass04','010-1234-5675','member04@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member05','pass05','010-1234-5674','member05@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member06','pass06','010-1234-5673','member06@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member07','pass07','010-1234-5672','member07@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member08','pass08','010-1234-5671','member08@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member09','pass09','010-1234-5670','member09@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member10','pass10','010-1234-5669','member10@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member11','pass11','010-1234-5668','member11@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member12','pass12','010-1234-5667','member12@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member13','pass13','010-1234-5666','member13@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member14','pass14','010-1234-5665','member14@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member15','pass15','010-1234-5664','member15@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member16','pass16','010-1234-5663','member16@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member17','pass17','010-1234-5662','member17@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member18','pass18','010-1234-5661','member18@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member19','pass19','010-1234-5660','member19@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member20','pass20','010-1234-5659','member20@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member21','pass21','010-1234-5658','member21@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member22','pass22','010-1234-5657','member22@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member23','pass23','010-1234-5656','member23@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member24','pass24','010-1234-5655','member24@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member25','pass25','010-1234-5654','member25@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member26','pass26','010-1234-5653','member26@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member27','pass27','010-1234-5652','member27@kh.com','N');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member28','pass28','010-1234-5651','member28@kh.com','Y');

INSERT INTO MEMBER (MEM_NO, MEM_ID, MEM_PWD, PHONE, EMAIL, STATUS) VALUES (SEQ_MEM_NO.NEXTVAL,'member29','pass29','010-1234-5650','member29@kh.com','N');
--MUSIC데이터
SET DEFINE OFF
INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Specialz', 'king Gnu', 'JPOP', '03:59', 'https://youtu.be/MIbt_Yn_rdw', 'Y', 0, 'resources/icon/musicAlbumCover/Specialz.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'KICK BACK', 'Kensi Yonezu', 'JPOP', '03:14', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/KICK BACK.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Lemon', 'Kensi Yonezu', 'JPOP', '04:16', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Lemon.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Inferno', 'Mrs.Green Apple', 'JPOP', '03:33', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Inferno.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Some Like Hot!!', 'SpyAir', 'JPOP', '03:12', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Some Like Hot!!.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Gurenge', 'Lisa', 'JPOP', '03:58', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Gurenge.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Zankyosanka', 'Aimer', 'JPOP', '03:05', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Zankyosanka.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '사랑을 전하고 싶다던가', '아이묭', 'JPOP', '04:31', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/사랑을 전하고 싶다던가.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Betelgeuse', 'Yuuri', 'JPOP', '03:51', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Betelgeuse.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'CryBaby', 'Official Hige Dandism', 'JPOP', '04:02', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/CryBaby.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '푸르름이 사는 곳', '키타니 타츠야', 'JPOP', '03:14', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/푸르름이 사는 곳.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '밤을달리다', 'YOASOBI', 'JPOP', '04:19', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/밤을달리다.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '피날래', 'eill', 'JPOP', '04:01', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/피날래.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '벛꽃만월', 'SpyAir', 'JPOP', '03:33', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/벛꽃만월.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'apdo', 'ado', 'JPOP', '03:58', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/apdo.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Night dancer', 'imase', 'JPOP', '03:31', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Night dancer.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Kaikai Kitan', 'Eve', 'JPOP', '03:42', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Kaikai Kitan.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Glorious days', 'Three Lights Down Kings', 'JPOP', '03:59', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Glorious days.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Shutter', 'Yuuri', 'JPOP', '04:09', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Shutter.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Sakayme', 'King Gnu', 'JPOP', '05:08', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Sakayme.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'merry-go-round', 'Yuuri', 'JPOP', '04:17', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/merry-go-round.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Avid', 'SawanoHiroyuki', 'JPOP', '04:09', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Avid.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '아무것도 아니야', 'RADWIMPS', 'JPOP', '05:48', NULL, 'Y', 1, 'resources/icon/musicAlbumCover/아무것도 아니야.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Sparkle', 'RADWIMPS', 'JPOP', '04:38', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Sparkle.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Spnning Globe', 'Kensi Yonezu', 'JPOP', '04:30', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Spnning Globe.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Bye bye my blue', '백예린', 'R&B', '03:23', 'https://www.youtube.com/watch?v=WbhK3wMXluE', 'Y', 0, 'resources/icon/musicAlbumCover/Bye bye my blue.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Vancouver', 'BIG Naughty(서동현)', 'R&B', '03:36', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Vancouver.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'D', 'DEAN', 'R&B', '03:49', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/D.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '비', '폴킴', 'R&B', '03:57', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/비.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '잊어버리지마(feat.태연)', 'Crush', 'R&B', '03:39', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/잊어버리지마(feat.태연).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '와르르♥', 'Colde(콜드)', 'R&B', '04:32', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/와르르♥.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'My Everything', '신용재(2F), Paul Blanco', 'R&B', '04:48', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/My Everything.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'All I Wanna Do(feat. Hoody, Loco)', '박재범', 'R&B', '03:36', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/All I Wanna Do(feat. Hoody, Loco).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '벌써 일년', '브라운 아이즈', 'R&B', '03:27', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/벌써 일년.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '떠나', 'THAMA, Jayci yucca(제이씨유카)', 'R&B', '04:07', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/떠나.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Thirsty', 'aespa', 'R&B', '03:13', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Thirsty.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Boat', '죠지', 'R&B', '03:12', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Boat.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '너는 나 나는 너', '지코', 'R&B', '03:33', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/너는 나 나는 너.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Hurt', 'New Jeans', 'R&B', '02:56', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Hurt.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '팔레트(feat. G-DRAGON)', '아이유', 'R&B', '03:37', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/팔레트(feat. G-DRAGON).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '곁에 있어줘(feat. 원슈타인)', 'SOLE(쏠)', 'R&B', '03:11', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/곁에 있어줘(feat. 원슈타인).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '자니(feat.다이나믹듀오)', '프라이머리', 'R&B', '03:54', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/자니(feat.다이나믹듀오).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '양화대교', 'Zion.T', 'R&B', '03:49', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/양화대교.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '비도 오고 그래서(feat. 신용재)', '헤이즈', 'R&B', '03:25', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/비도 오고 그래서(feat. 신용재).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Trip(feat. Hannah)', '릴러말즈', 'R&B', '03:54', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Trip(feat. Hannah).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Summer(feat. 비오)', 'Paul Blanco', 'R&B', '03:19', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Summer(feat. 비오).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Nerdy Love(feat. 백예린)', 'pH-1', 'R&B', '03:16', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Nerdy Love(feat. 백예린).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '어떻게 지내', '오반', 'R&B', '03:50', NULL, 'Y', 2, 'resources/icon/musicAlbumCover/어떻게 지내.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '오늘 취하면(feat. 창모)', '수란', 'R&B', '03:52', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/오늘 취하면(feat. 창모).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'silly silly Love', '권진아', 'R&B', '03:34', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/silly silly Love.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Alone(feat. 쏠(SOLE), 다운(Dvwn))', 'Cosmic Boy', 'R&B', '03:20', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Alone(feat. 쏠(SOLE), 다운(Dvwn)).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'To Be With You', 'Mr. Big', 'Rock', '03:30', 'https://youtu.be/L6-uJLteKek?si=Wej490cZTH2q6ZkY', 'Y', 0, 'resources/icon/musicAlbumCover/To Be With You.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Long, Long Way from Home', 'Foreigner', 'Rock', '02:53', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Long, Long Way from Home.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Too Daze Gone', 'Billy Squier', 'Rock', '04:04', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Too Daze Gone.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Wanted Dead Or Alive', 'Bon Jovi', 'Rock', '05:07', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Wanted Dead Or Alive.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'We''re an American Band', 'Grand Funk Railroad', 'Rock', '03:27', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/We''re an American Band.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Just As Through With You', 'Nine Days', 'Rock', '03:54', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Just As Through With You.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Eye Of The Tiger', 'Survivor', 'Rock', '04:04', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Eye Of The Tiger.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Butterflies and Hurricanes', 'Muse ', 'Rock', '05:02', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Butterflies and Hurricanes.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Ready Aim Fire', 'Blue Stahli', 'Rock', '03:05', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Ready Aim Fire.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Starless', 'Crossfade ', 'Rock', '03:55', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Starless.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'November Rain', 'Guns N'' Roses', 'Rock', '08:56', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/November Rain.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Cherry Pie', 'Warrant ', 'Rock', '03:21', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Cherry Pie.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Sgt. Pepper''s Lonely Hearts Club Band', 'The Beatles', 'Rock', '02:02', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Sgt. Pepper''s Lonely Hearts Club Band.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Carry On Wayward Son', 'Kansas ', 'Rock', '05:23', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Carry On Wayward Son.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Numb', 'Linkin Park', 'Rock', '03:08', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Numb.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Smells Like Teen Spirit', 'Nirvana ', 'Rock', '04:39', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Smells Like Teen Spirit.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Kashmir', 'Led Zeppelin', 'Rock', '08:37', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Kashmir.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '(I Can''t Get No) Satisfaction', 'The Rolling Stones', 'Rock', '03:54', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/(I Can''t Get No) Satisfaction.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Heat Of The Moment', 'Asia ', 'Rock', '03:08', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Heat Of The Moment.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'With Or Without You', 'U2', 'Rock', '04:52', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/With Or Without You.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Burn', 'Deep Purple', 'Rock', '06:04', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Burn.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Somebody To Love', 'Queen ', 'Rock', '05:09', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Somebody To Love.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Highway to Hell', 'AC/DC', 'Rock', '03:28', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Highway to Hell.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'I Don''t Want to Miss a Thing', 'Aerosmith ', 'Rock', '04:52', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/I Don''t Want to Miss a Thing.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Shine ', 'Collective Soul', 'Rock', '04:39', NULL, 'Y', 3, 'resources/icon/musicAlbumCover/Shine.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Take Five
', 'Dave Brubeck', 'Jazz', '05:29', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Take Five.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Out of Time', 'The Weeknd', 'POP', '03:35', 'https://youtu.be/2fDzCWNS3ig?si=Xt_9AyLEpdKM5QNU', 'Y', 0, 'resources/icon/musicAlbumCover/Out of Time.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Steal The Show (From “엘리멘탈”)', 'Lauv', 'POP', '03:37', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Steal The Show (From “엘리멘탈”).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'I Don''t Think That I Like Her', 'Charlie Puth', 'POP', '03:09', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/I Don''t Think That I Like Her.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Dangerously', 'Charlie Puth', 'POP', '03:20', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Dangerously.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'STAY', 'The Kid LAROI, Justin Bieber', 'POP', '02:22', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/STAY.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'That''s Hilarious', 'Charlie Puth', 'POP', '02:25', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/That''s Hilarious.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Dreamers', '정국', 'POP', '03:22', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Dreamers.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, '2002', 'Anne-Marie', 'POP', '03:07', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/2002.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'I''m Not The Only One', 'Sam Smith', 'POP', '04:00', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/I''m Not The Only One.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Shape of You', 'Ed Sheeran', 'POP', '03:54', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Shape of You.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Blinding Lights', 'The Weeknd', 'POP', '03:22', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Blinding Lights.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Without Me', 'Eminem', 'POP', '04:51', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Without Me.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Another One Bites The Dust', 'Queen', 'POP', '03:35', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Another One Bites The Dust.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Feels(feat. 퍼렐 윌리엄스(Pharrell Williams), Katy Perry(케이티 페리), Big Sean)', 'Calvin Harris', 'POP', '03:44', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Feels(feat. 퍼렐 윌리엄스(Pharrell Williams), Katy Perry(케이티 페리), Big Sean).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Starboy(feat. Daft Punk)', 'The Weeknd', 'POP', '03:51', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Starboy(feat. Daft Punk).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Treasure', 'Bruno Mars', 'POP', '02:59', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Treasure.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Leave The Door Open', 'Bruno Mars, Anderson .Paak 및 Silk Sonic', 'POP', '04:03', NULL, 'Y', 4, 'resources/icon/musicAlbumCover/Leave The Door Open.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Save Your Tears', 'The Weeknd', 'POP', '03:36', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Save Your Tears.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Day 1 ◑', 'HONNE', 'POP', '03:54', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Day 1 ◑.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Lost Stars', 'Adam Levine', 'POP', '04:28', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Lost Stars.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'This Love', 'Maroon 5', 'POP', '03:27', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/This Love.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Young, Wild & Free(feat. Bruno Mars)', 'Wiz Khalifa 및 Snoop Dogg', 'POP', '03:28', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Young, Wild & Free(feat. Bruno Mars).jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'No One Else Like You', 'Adam Levine', 'POP', '03:29', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/No One Else Like You.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Bad guy', 'Billie Eilish', 'POP', '03:15', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Bad guy.jpg', SYSDATE);

INSERT INTO MUSIC (MUS_NO, MUS_NAME, MUS_ART, MUS_GEN, MUS_TIME, MUS_MV, STATUS, COUNT, ALBUM_PATH, ENROLL_DATE) 
VALUES (SEQ_MUS_NO.NEXTVAL, 'Snowman', 'Sia', 'POP', '02:46', NULL, 'Y', 0, 'resources/icon/musicAlbumCover/Snowman.jpg', SYSDATE);

--플레이리스트 더미데이터
INSERT INTO PLAYLIST (MUS_NO, MEM_NO)
VALUES (100, 3);
INSERT INTO PLAYLIST (MUS_NO, MEM_NO)
VALUES (151, 3);
INSERT INTO PLAYLIST (MUS_NO, MEM_NO)
VALUES (125, 3);
INSERT INTO PLAYLIST (MUS_NO, MEM_NO)
VALUES (177, 3);

--ATTACHMENT 더미데이터

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,100,'Specialz.jpg','Specialz.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,101,'KICK BACK.jpg','KICK BACK.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,102,'Lemon.jpg','Lemon.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,103,'Inferno.jpg','Inferno.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,104,'Some Like Hot!!.jpg','Some Like Hot!!.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,105,'Gurenge.jpg','Gurenge.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,106,'Zankyosanka.jpg','Zankyosanka.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,107,'사랑을 전하고 싶다던가.jpg','사랑을 전하고 싶다던가.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,108,'Betelgeuse.jpg','Betelgeuse.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,109,'CryBaby.jpg','CryBaby.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,110,'푸르름이 사는 곳.jpg','푸르름이 사는 곳.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,111,'밤을달리다.jpg','밤을달리다.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,112,'피날래.jpg','피날래.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,113,'벛꽃만월.jpg','벛꽃만월.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,114,'apdo.jpg','apdo.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,115,'Night dancer.jpg','Night dancer.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,116,'Kaikai Kitan.jpg','Kaikai Kitan.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,117,'Glorious days.jpg','Glorious days.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,118,'Shutter.jpg','Shutter.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,119,'Sakayme.jpg','Sakayme.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,120,'merry-go-round.jpg','merry-go-round.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,121,'Avid.jpg','Avid.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,122,'아무것도 아니야.jpg','아무것도 아니야.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,123,'Sparkle.jpg','Sparkle.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,124,'Spnning Globe.jpg','Spnning Globe.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,125,'Bye bye my blue.jpg','Bye bye my blue.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,126,'Vancouver.jpg','Vancouver.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,127,'D.jpg','D.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,128,'비.jpg','비.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,129,'잊어버리지마(feat.태연).jpg','잊어버리지마(feat.태연).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,130,'와르르♥.jpg','와르르♥.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,131,'My Everything.jpg','My Everything.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,132,'All I Wanna Do(feat. Hoody, Loco).jpg','All I Wanna Do(feat. Hoody, Loco).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,133,'벌써 일년.jpg','벌써 일년.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,134,'떠나.jpg','떠나.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,135,'Thirsty.jpg','Thirsty.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,136,'Boat.jpg','Boat.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,137,'너는 나 나는 너.jpg','너는 나 나는 너.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,138,'Hurt.jpg','Hurt.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,139,'팔레트(feat. G-DRAGON).jpg','팔레트(feat. G-DRAGON).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,140,'곁에 있어줘(feat. 원슈타인).jpg','곁에 있어줘(feat. 원슈타인).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,141,'자니(feat.다이나믹듀오).jpg','자니(feat.다이나믹듀오).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,142,'양화대교.jpg','양화대교.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,143,'비도 오고 그래서(feat. 신용재).jpg','비도 오고 그래서(feat. 신용재).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,144,'Trip(feat. Hannah).jpg','Trip(feat. Hannah).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,145,'Summer(feat. 비오).jpg','Summer(feat. 비오).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,146,'Nerdy Love(feat. 백예린).jpg','Nerdy Love(feat. 백예린).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,147,'어떻게 지내.jpg','어떻게 지내.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,148,'오늘 취하면(feat. 창모).jpg','오늘 취하면(feat. 창모).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,149,'silly silly Love.jpg','silly silly Love.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,150,'Alone(feat. 쏠(SOLE), 다운(Dvwn)).jpg','Alone(feat. 쏠(SOLE), 다운(Dvwn)).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,151,'To Be With You.jpg','To Be With You.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,152,'Long, Long Way from Home.jpg','Long, Long Way from Home.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,153,'Too Daze Gone.jpg','Too Daze Gone.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,154,'Wanted Dead Or Alive.jpg','Wanted Dead Or Alive.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,155,'We''re an American Band.jpg','We''re an American Band.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,156,'Just As Through With You.jpg','Just As Through With You.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,157,'Eye Of The Tiger.jpg','Eye Of The Tiger.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,158,'Butterflies and Hurricanes.jpg','Butterflies and Hurricanes.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,159,'Ready Aim Fire.jpg','Ready Aim Fire.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,160,'Starless.jpg','Starless.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,161,'November Rain.jpg','November Rain.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,162,'Cherry Pie.jpg','Cherry Pie.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,163,'Sgt. Pepper''s Lonely Hearts Club Band.jpg','Sgt. Pepper''s Lonely Hearts Club Band.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,164,'Carry On Wayward Son.jpg','Carry On Wayward Son.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,165,'Numb.jpg','Numb.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,166,'Smells Like Teen Spirit.jpg','Smells Like Teen Spirit.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,167,'Kashmir.jpg','Kashmir.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,168,'(I Can''t Get No) Satisfaction.jpg','(I Can''t Get No) Satisfaction.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,169,'Heat Of The Moment.jpg','Heat Of The Moment.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,170,'With Or Without You.jpg','With Or Without You.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,171,'Burn.jpg','Burn.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,172,'Somebody To Love.jpg','Somebody To Love.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,173,'Highway to Hell.jpg','Highway to Hell.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,174,'I Don''t Want to Miss a Thing.jpg','I Don''t Want to Miss a Thing.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,175,'Shine.jpg','Shine.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,176,'Take Five.jpg','Take Five.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,177,'Out of Time.jpg','Out of Time.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,178,'Steal The Show (From “엘리멘탈”).jpg','Steal The Show (From “엘리멘탈”).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,179,'I Don''t Think That I Like Her.jpg','I Don''t Think That I Like Her.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,180,'Dangerously.jpg','Dangerously.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,181,'STAY.jpg','STAY.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,182,'That''s Hilarious.jpg','That''s Hilarious.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,183,'Dreamers.jpg','Dreamers.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,184,'2002.jpg','2002.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,185,'I''m Not The Only One.jpg','I''m Not The Only One.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,186,'Shape of You.jpg','Shape of You.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,187,'Blinding Lights.jpg','Blinding Lights.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,188,'Without Me.jpg','Without Me.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,189,'Another One Bites The Dust.jpg','Another One Bites The Dust.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,190,'Feels(feat. 퍼렐 윌리엄스(Pharrell Williams), Katy Perry(케이티 페리), Big Sean).jpg','Feels(feat. 퍼렐 윌리엄스(Pharrell Williams), Katy Perry(케이티 페리), Big Sean).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,191,'Starboy(feat. Daft Punk).jpg','Starboy(feat. Daft Punk).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,192,'Treasure.jpg','Treasure.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,193,'Leave The Door Open.jpg','Leave The Door Open.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,194,'Save Your Tears.jpg','Save Your Tears.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,195,'Day 1 ◑.jpg','Day 1 ◑.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,196,'Lost Stars.jpg','Lost Stars.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,197,'This Love.jpg','This Love.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,198,'Young, Wild & Free(feat. Bruno Mars).jpg','Young, Wild & Free(feat. Bruno Mars).jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,199,'No One Else Like You.jpg','No One Else Like You.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,200,'Bad guy.jpg','Bad guy.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

INSERT INTO ATTACHMENT (FILE_NO, REF_MNO, ORIGIN_NAME, CHANGE_NAME, FILE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES (SEQ_FILE_NO.NEXTVAL,201,'Snowman.jpg','Snowman.jpg','resources/icon/musicAlbumCover/',SYSDATE,1,'Y');

commit;